[package]
name = "server-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

configparser = "3.0.0"
envconfig = "0.10.0"
env_logger = "0.9.0"
log = "0.4"
signal-hook = "0.3.13"
